# Generated by Django 5.0.6 on 2024-11-06 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('max_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('productentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.productentity')),
            ],
            bases=('main.productentity',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.productentity')),
                ('ean', models.CharField(max_length=13, unique=True)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
            bases=('main.productentity',),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField()),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productentity')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.option')),
            ],
        ),
        migrations.AddField(
            model_name='productentity',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_handled', models.BooleanField(default=False)),
                ('retail_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('Brand', 'Brand'), ('ProductLine', 'ProductLine'), ('Product', 'Product')], max_length=20)),
                ('is_draft', models.BooleanField()),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aspect')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questionnaire'),
        ),
        migrations.CreateModel(
            name='QuestionnaireEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productentity')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aspect')),
                ('product_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productentity')),
            ],
        ),
        migrations.CreateModel(
            name='Subaspect',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aspect')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subaspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subaspect'),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_answer', models.BooleanField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answer')),
                ('retail_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='main.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
        ),
        migrations.CreateModel(
            name='MyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='AspectTotalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.aspect')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect_total_scores', to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('productentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.productentity')),
                ('parent_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
            ],
            bases=('main.productentity',),
        ),
        migrations.AddField(
            model_name='product',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productline'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(fields=('product_category', 'aspect', 'entity_type'), name='unique_productcategory_aspect_entitytype'),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireentity',
            unique_together={('questionnaire', 'product_entity')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('aspect', 'product_entity')},
        ),
        migrations.AlterUniqueTogether(
            name='myproducts',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='aspecttotalscore',
            unique_together={('product', 'aspect')},
        ),
    ]
