# Generated by Django 5.0.6 on 2024-12-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_myproducts_unique_together_myproducts_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='is_draft',
        ),
    ]
