# Generated by Django 5.0.6 on 2025-03-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_questionnaire_is_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productline',
            old_name='parent_brand',
            new_name='brand_fk',
        ),
    ]
