# Generated by Django 5.0.6 on 2025-04-09 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_parent_brand_productline_brand_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token sent to the user for signup.', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the token was created.')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when the token will expire.')),
                ('is_used', models.BooleanField(default=False, help_text='Indicates if the token has already been used for signup.')),
                ('brand', models.ForeignKey(help_text='The brand the new user will be associated with.', on_delete=django.db.models.deletion.CASCADE, to='main.brand')),
                ('company', models.ForeignKey(help_text='The company the new user will belong to.', on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('role', models.ForeignKey(help_text='The role the new user will be assigned.', on_delete=django.db.models.deletion.CASCADE, to='main.role')),
            ],
            options={
                'verbose_name': 'Signup Token',
                'verbose_name_plural': 'Signup Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
