# Generated by Django 5.0.6 on 2025-04-16 13:39
from django.db import migrations

ROLES_TO_CREATE = ['Admin', 'Editor', 'ManufacturingUser', 'RetailUser', 'Viewer']

def populate_roles(apps, schema_editor):
    """
    Creates the standard Role objects if they don't exist.
    """
    # Use apps.get_model to get the historical version of the Role model
    Role = apps.get_model('main', 'Role')
    db_alias = schema_editor.connection.alias # Get the database alias being used

    print(f"\n  Applying migration populate_roles on database '{db_alias}':")

    for role_name in ROLES_TO_CREATE:
        # get_or_create prevents errors if the role already exists
        role, created = Role.objects.using(db_alias).get_or_create(name=role_name)
        if created:
            print(f"    - Created Role: {role_name}")
        else:
            print(f"    - Role already exists: {role_name}")

def remove_roles(apps, schema_editor):
    """
    Removes the standard Role objects created by populate_roles.
    Use with caution, especially if other data references these roles.
    """
    Role = apps.get_model('main', 'Role')
    db_alias = schema_editor.connection.alias

    print(f"\n  Reversing migration populate_roles on database '{db_alias}':")

    # Filter for the specific roles and delete them
    deleted_count, _ = Role.objects.using(db_alias).filter(
        name__in=ROLES_TO_CREATE
    ).delete()

    print(f"    - Deleted {deleted_count} roles: {', '.join(ROLES_TO_CREATE)}")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_signuptoken'),
    ]

    operations = [
        # Run the Python functions to populate/remove roles
        migrations.RunPython(populate_roles, remove_roles),
    ]