# Generated by Django 5.0.6 on 2025-04-22 07:05

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_populate_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(help_text='Enter the 8 or 13-digit EAN code.', max_length=13, unique=True, validators=[main.validators.EanValidator()]),
        ),
    ]
