# Generated by Django 5.0.6 on 2025-05-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_ean'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentity',
            name='questionnaires',
            field=models.ManyToManyField(through='main.QuestionnaireEntity', to='main.questionnaire'),
        ),
    ]
