# Generated by Django 5.0.6 on 2025-05-05 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productentity_questionnaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentity',
            name='product_category',
        ),
        migrations.AddField(
            model_name='productline',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productcategory'),
        ),
    ]
