# Generated by Django 5.0.6 on 2025-05-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_productentity_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='ProductBrand',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='entity_type',
            field=models.CharField(choices=[('ProductBrand', 'ProductBrand'), ('ProductLine', 'ProductLine'), ('Product', 'Product')], max_length=20),
        ),
    ]
