# Generated by Django 5.0.6 on 2025-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_brand_productbrand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductModel',
        ),
        migrations.RenameField(
            model_name='aspecttotalscore',
            old_name='product',
            new_name='product_model',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='brand',
            new_name='product_brand',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='entity_type',
            field=models.CharField(choices=[('ProductBrand', 'ProductBrand'), ('ProductLine', 'ProductLine'), ('ProductModel', 'ProductModel')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='aspecttotalscore',
            unique_together={('product_model', 'aspect')},
        ),
    ]
