# Generated by Django 5.0.6 on 2025-08-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_product_productmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspect',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
