# Generated by Django 5.0.6 on 2025-08-22 13:05

import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aspect_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='ean',
        ),
        migrations.CreateModel(
            name='EAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(help_text='Enter the 8 or 13-digit EAN code.', max_length=13, unique=True, validators=[main.validators.EanValidator()])),
                ('name', models.CharField(help_text="Description of this specific EAN variant (e.g., 'iPhone 13 128GB Blue')", max_length=255)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eans', to='main.productmodel')),
            ],
            options={
                'verbose_name': 'EAN',
                'verbose_name_plural': 'EANs',
            },
        ),
    ]
