# Generated by Django 5.0.6 on 2025-09-16 12:12

from django.db import migrations, models


def migrate_is_selected_to_is_true_is_false(apps, schema_editor):
    """
    Migrate existing is_selected values to the new is_true/is_false fields.
    - is_selected=True becomes is_true=True, is_false=False
    - is_selected=False becomes is_true=False, is_false=True
    """
    Answer = apps.get_model('main', 'Answer')
    
    # Update all answers that were previously selected (is_selected=True)
    Answer.objects.filter(is_selected=True).update(is_true=True, is_false=False)
    
    # Update all answers that were previously unselected (is_selected=False)
    Answer.objects.filter(is_selected=False).update(is_true=False, is_false=True)


def reverse_migrate_is_true_is_false_to_is_selected(apps, schema_editor):
    """
    Reverse migration: convert is_true/is_false back to is_selected.
    - is_true=True becomes is_selected=True
    - is_false=True becomes is_selected=False
    - Both False (unknown state) becomes is_selected=False
    """
    Answer = apps.get_model('main', 'Answer')
    
    # Convert is_true=True to is_selected=True
    Answer.objects.filter(is_true=True).update(is_selected=True)
    
    # Convert is_false=True or both False to is_selected=False
    Answer.objects.filter(is_false=True).update(is_selected=False)
    Answer.objects.filter(is_true=False, is_false=False).update(is_selected=False)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_separate_ean_table'),
    ]

    operations = [
        # Add the new fields with default values
        migrations.AddField(
            model_name='answer',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_false',
            field=models.BooleanField(default=False),
        ),
        
        # Migrate data from is_selected to is_true/is_false
        migrations.RunPython(
            migrate_is_selected_to_is_true_is_false,
            reverse_migrate_is_true_is_false_to_is_selected
        ),
        
        # Remove the old field
        migrations.RemoveField(
            model_name='answer',
            name='is_selected',
        ),
    ]
