# Generated by Django 5.0.6 on 2025-09-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_replace_is_selected_with_is_true_is_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="definition",
            field=models.TextField(blank=True, null=True),
        ),
    ]
