# Generated by Django 5.0.6 on 2025-09-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_replace_is_selected_with_is_true_is_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_single_choice",
            field=models.BooleanField(
                default=False,
                help_text="If True, only one option can be selected as True or False.",
            ),
        ),
    ]
