# Generated by Django 5.0.6 on 2025-09-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_option_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="purpose",
            field=models.TextField(blank=True, null=True),
        ),
    ]
