# Generated by Django 5.0.6 on 2025-09-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_question_is_single_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="is_single_choice",
            field=models.BooleanField(
                default=False,
                help_text="If true, only one option can be selected (single-choice). If false, multiple options can be selected.",
            ),
        ),
    ]
