# Generated by Django 5.0.6 on 2025-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_question_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="source",
            field=models.TextField(blank=True, null=True),
        ),
    ]
