# Generated by Django 5.0.6 on 2025-09-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_answer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspecttotalscore',
            name='isAnswered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspecttotalscore',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
