# Generated by Django 5.0.6 on 2025-10-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_question_is_single_choice'),
        ('main', '0017_answer_source'),
    ]

    operations = [
    ]
