# Generated by Django 5.0.6 on 2025-10-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_answer_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspect',
            name='icon',
        ),
    ]
