# Generated by Django 5.0.6 on 2025-10-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_merge_20251001_0938'),
        ('main', '0018_remove_aspect_icon'),
    ]

    operations = [
    ]
