# Generated by Django 5.0.6 on 2025-10-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merge_20251003_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='can_edit_question_answers',
            field=models.BooleanField(default=False),
        ),
    ]
