# Generated by Django 5.2.7 on 2025-10-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_company_can_edit_question_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Questionnaire Category',
                'verbose_name_plural': 'Questionnaire Categories',
            },
        ),
        migrations.RemoveConstraint(
            model_name='questionnaire',
            name='unique_productcategory_aspect_entitytype',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='product_category',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='questionnaire_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='main.questionnairecategory'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questionnaire_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.questionnairecategory'),
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(fields=('questionnaire_category', 'aspect', 'entity_type'), name='unique_questionnairecategory_aspect_entitytype'),
        ),
    ]
