# Generated by Django 5.0.6 on 2025-10-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_company_can_edit_question_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="context",
            field=models.TextField(blank=True, null=True),
        ),
    ]
