# Generated by Django 5.0.6 on 2025-10-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_aspecttotalscore_isanswered_aspecttotalscore_status'),
        ('main', '0020_company_can_edit_question_answers'),
    ]

    operations = [
    ]
