# Generated by Django 5.0.6 on 2025-10-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merge_20251006_1249'),
        ('main', '0020_company_can_edit_question_answers'),
    ]

    operations = [
    ]
