# Generated by Django 5.0.6 on 2025-10-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_merge_20251008_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspecttotalscore',
            name='isAnswered',
        ),
        migrations.RemoveField(
            model_name='aspecttotalscore',
            name='status',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='isAnswered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
