# Generated by Django 5.0.6 on 2025-11-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_answer_context'),
        ('main', '0021_merge_20251030_1109'),
    ]

    operations = [
    ]
