# Generated by Django 5.0.6 on 2026-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_merge_20251030_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ean',
            name='ean',
            field=models.CharField(help_text='Enter the 8 or 13-digit EAN code.', max_length=15, unique=True),
        ),
    ]
