# Generated by Django 5.0.6 on 2025-11-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_merge_20251030_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="suggestion_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
