# Generated by Django 5.0.6 on 2025-10-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_aspecttotalscore_isanswered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='status',
        ),
    ]
