# Generated by Django 5.0.6 on 2025-11-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_questionnairecategory_and_more'),
        ('main', '0022_merge_0021_answer_context_0021_merge_20251030_1109'),
    ]

    operations = [
    ]
