# Generated by Django 5.0.6 on 2025-12-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_query_suggestion_text"),
        ("main", "0023_merge_20251113_1500"),
        ("main", "0023_remove_productmodel_status"),
    ]

    operations = []
