# Generated by Django 5.0.6 on 2026-02-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_aianswerfeedback'),
        ('main', '0024_merge_20251214_1945'),
    ]

    operations = [
    ]
