# Generated by Django 5.0.6 on 2026-02-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_ean_ean'),
        ('main', '0025_merge_0024_aianswerfeedback_0024_merge_20251214_1945'),
    ]

    operations = [
    ]
