# Generated by Django 5.0.6 on 2026-02-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_merge_20260212_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instructions',
            field=models.TextField(blank=True, help_text='Specific instructions for the AI on how to answer this question.', null=True),
        ),
    ]
